### ISSUE TITLE
Mace issues.

### ISSUE THREAD

**Issue by MythicalTrashcan** [Derec-Mods/Mace-Mod#1]
1. Idk why but you can use the Mace like a sword. So just attack anything without jumping to swing.
2. Mace crafting recipe is pretty cheap for being better than all the swords.
3. Mace can be enchanted with sharpness. (there also isn't new enchants)

I think the Mace is like a retexture iron sword with it's falling attack abilities.

**Comment by MythicalTrashcan** [comment]
Also you should provide source.

**Comment by DereC4** [comment]
> 1. Idk why but you can use the Mace like a sword. So just attack anything without jumping to swing.
> 2. Mace crafting recipe is pretty cheap for being better than all the swords.
> 3. Mace can be enchanted with sharpness. (there also isn't new enchants)
> 
> I think the Mace is like a retexture iron sword with it's falling attack abilities.

Oh hey there buddy! Thanks for your reply

**Comment by DereC4** [comment]
Oops it was originally based on the sword code but after testing on 24w13a today, it looks like you're right! It doesn't behave like a sword. This fix will be rolling out when I finish my classwork. As for point 3, the new enchants are out but not for some of the versions like 1.16.5 yet. 

It's my fault for not making the issue requirements clear but lemme know which version of the mod you're actually using and which Minecraft version, and that'll make it much easier to debug. 

Again thanks for your help!

**Comment by MythicalTrashcan** [comment]
I mainly use 1.12.2 and 1.16.5. I was wondering why a version that released the same day as the enchantment update for like 1.19 and 1.20 wasn't included in the 1.12 version.

**Comment by DereC4** [comment]
Oh that's a great question! I'm not if you're sure with how Minecraft modding has journey'd but if you've played for a while you may remember a period of time when 75% of mods were basically stuck at 1.12.2 and not updating even though the game already moved on to 1.16.5. 

I recommend reading this [comment thread](https://www.reddit.com/r/feedthebeast/comments/1bpl2z7/i_recall_1710_and_1122_being_very_significant/) but I'll phrase my favorite part for you

> 1.13 in particular led to Forge rewriting a bunch of their codebase. As such, it took a lot of work to port mods over, and so many mods and packs stayed on 1.12 for quite a while as there just wasn't enough content on 1.13 compared to the highly mature 1.12 scene. Forge did release on every version, but the scene didn't adopt those versions. Since then, Minecraft releases have been so frequent, and Forge's refactor made it quick enough for them to release after Minecraft that no version has become entrenched in quite the same way. And there haven't been such drastic changes in the codebase to require total mod rewrites to update. So modders have mostly been targeting the most recent patch for a long time.

That's why I can rapidly address issues on the other versions a lot quicker than 1.12, which is way before the threshold. To work on 1.12, I actually had to recreate the mod from scratch and the only reason I could do it in a day was because of the low content this mod have. Rest assured, I have no plans to abandon the 1.12 work but it just takes a lot more work since that was more than half a decade ago, and a lot of the codebase is deprecated now. 

1.16.5 got the enchantment update a day ago btwww so check it out! 

Also I'm actively in class so my apologies if I don't reply fast

**Comment by DereC4** [comment]
it's been two weeks without comment from you so I'll go ahead and close this now! What you detailed was addressed dw
