### ISSUE TITLE
Mace doesn't scale with damage attribute.

### ISSUE THREAD

**Issue by wabeb325** [Derec-Mods/Mace-Mod#3]
Well, this is a suggestion or reminder so to speak, but the changes from the new versions to version 1.18.2 and 1.12.2 still need to be implemented.

Edit: While testing the mod I saw a few bugs to notice:

- The mace does not scale with artifacts that grant attack damage attribute, example of this are artifact gloves.
- It would be nice to add a config file to configure the maximum damage cap layer of the mace.

**Comment by DereC4** [comment]
OK so your first bullet point i actually did do this at the very very beginning 

But what Mojang did with the latest snapshot is the mace drop damage scales with ONLY fall distance and density etc now and idk that felt wrong to me bit it is what it is, so I had to remove the attribute scaling. I think i will add that back though because it just makes sense

**Comment by DereC4** [comment]
Btw can you split your issue into two? One for each bullet point? 

The first is a bug I believe (though it is how vanilla intends), and the second is a feature request and i'd love to keep them as separate tasks to do

**Comment by wabeb325** [comment]
Ok, I'm going to set this one as the bug.

**Comment by DereC4** [comment]
kk

**Comment by DereC4** [comment]
Closing this now because it now matches intended Mojang behavior, and the base strength does actually affect the initial dmg of the mace
